# Generated by Django 2.0.5 on 2018-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('epassword', models.CharField(default='', max_length=128)),
                ('phone_number', models.CharField(default=0, max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('gstin', models.CharField(blank=True, default='', max_length=50)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('upassword', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
