# Generated by Django 2.1.4 on 2018-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('upassword', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('epassword', models.CharField(default='', max_length=128)),
                ('month', models.CharField(default='', max_length=12)),
                ('status', models.CharField(default='Not Filed', max_length=11)),
            ],
        ),
    ]
